import type { TransactionContext } from "../ports";

/**
 * A RegistrationIntent's exact lifetime (the registration specification):
 * 600 seconds in epoch milliseconds, fixed by the `expires_at =
 * created_at + 600000` storage CHECK.
 */
export const REGISTRATION_INTENT_TTL_MS = 600_000;

/**
 * The caller-supplied registration proof material: the unguessable
 * correlation `state`, the authentication `nonce`, and the
 * provider-independent `proofKeySecret` (the production adapter stores it
 * in the `pkce_verifier` column — OIDC/PKCE naming does not cross into the
 * application layer). All three are generated by the trusted boundary
 * before the serialized section runs.
 */
export type CreateRegistrationIntentInput = {
	readonly expectedIssuer: string;
	readonly expectedSubject: string;
	readonly state: string;
	readonly nonce: string;
	readonly proofKeySecret: string;
};

/**
 * The outcome of intent creation (the registration specification):
 *
 *   - `created` — a new status-active intent exists; `expiresAt` is the
 *     fixed `createdAt + 600_000`.
 *   - `alreadyRegistered` — the `(expectedIssuer, expectedSubject)` pair
 *     is already bound; nothing was mutated.
 */
export type CreateRegistrationIntentOutcome =
	| { readonly type: "created"; readonly expiresAt: number }
	| { readonly type: "alreadyRegistered" };

/**
 * Creates a registration intent inside the caller's already-open section
 * (issue #4 PR-4, the registration specification). The order is fixed:
 *
 *   binding lookup
 *   -> if bound: alreadyRegistered, no mutation
 *   -> supersede every status-active predecessor of the pair
 *      (including an already-expired one — the partial unique index on
 *      active rows must never block the replacement insert)
 *   -> insert the new intent at the section's frozen now_ms.
 *
 * Latest-wins: at most one status-active intent exists per external
 * identity.
 */
export function createRegistrationIntent(
	ctx: TransactionContext,
	input: CreateRegistrationIntentInput,
): CreateRegistrationIntentOutcome {
	const bound = ctx.identityBindings.findUserIdByExternal(
		input.expectedIssuer,
		input.expectedSubject,
	);
	if (bound !== undefined) {
		return { type: "alreadyRegistered" };
	}
	ctx.registrationIntents.supersedeActive(
		input.expectedIssuer,
		input.expectedSubject,
	);
	const intent = ctx.registrationIntents.insert({
		expectedIssuer: input.expectedIssuer,
		expectedSubject: input.expectedSubject,
		state: input.state,
		nonce: input.nonce,
		proofKeySecret: input.proofKeySecret,
		createdAt: ctx.nowMs,
		expiresAt: ctx.nowMs + REGISTRATION_INTENT_TTL_MS,
	});
	return { type: "created", expiresAt: intent.expiresAt };
}
